version: '3'

services: 
    rating-service:
        build: ./Rating/
        restart: always
        depends_on: 
            - mongodb

    communication-service:
        build: ./Communication/
        ports: 
            - 5000:5000
        restart: always
    
    ride-sharing-service:
        build: ./RideService/
        restart: always
        depends_on: 
            - communication-service

    nginx:
        build: ./nginx/
        ports: 
            - 104:80
        depends_on: 
            - rating-service
            - ride-sharing-service

    mongodb:
        image: mongo
        ports: 
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db
    
volumes:
    mongodb_data_container:
    
    
